Phase11 code review
Star-Academy/Winter99-CodeStar-AmirHessam-Bolandi pull request #9
Opened 2021-05-12 13:21 UTC by ahessamb

2021-05-15 17:09 UTC, BijanEisapour requested changes

2021-05-15 17:09 UTC, BijanEisapour commented on Phase08/SearchApp/SearchLibrary/Document.cs
> +        public string Content { get; set; }
<p dir='rtl' align='right'>
اگه فقط داری از get و set پیشفرض استفاده میکنی چرا گذاشتیشون؟
<br>
چرا از فیلد معمولی به جای Property استفاده نمیکنی؟

2021-05-15 17:09 UTC, BijanEisapour commented on Phase08/SearchApp/SearchLibrary/SearchContext.cs
> +            optionsBuilder.UseSqlServer(String.Format(@"Server={0};Database=SearchDB;Trusted_Connection=True;", server));
<p dir='rtl' align='right'>
به جای String.Format میتونی از String Interpolation استفاده کنید ...
</p>

```cs
optionsBuilder.UseSqlServer($"Server={server};Database=SearchDB;Trusted_Connection=True;");
```

2021-05-15 17:09 UTC, BijanEisapour commented on Phase08/SearchApp/console-app/Program.cs
> +        private const string SERVER = "localhost";
<p dir='rtl' align='right'>
تو C# واسه ثابت‌ها از PascalCase استفاده میکنیم
</p>

[Link](https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md)

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/Angular/src/app/back-ground-img/back-ground-img.component.html
> +<img src="assets/img/background.jpg" class="background-image" alt="background">
<p dir='rtl' align='right'>
تو alt به جای اینکه صرفاً بنویسی background بهتره یه توضیح در مورد محتویات داخل عکس بدی

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/Angular/src/app/app.component.ts
> +  title = 'Angular';
<p dir='rtl' align='right'>
جایی ازش استفاده نکردی پس پاکش کن

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/Angular/src/app/app.module.ts
> +import { MenuBarComponent } from './menu-bar/menu-bar.component';
<p dir='rtl' align='right'>
بهتره importهات رو مرتب کنی، مخصوصاً الان که تعدادشون زیاده 
<br>
مثلاً اونایی که از پکیج angular آوردی رو کنارِ هم بنویس، اونایی که مال خودت هستن رو کنارِ هم و ...

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/Angular/src/app/back-ground-img/back-ground-img.component.ts
> +
<p dir='rtl' align='right'>
اگه ازشون استفاده نمیکنی پاکشون کن

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/Angular/src/app/file-contents/file-contents.component.scss
> +  //color: rgb(223, 123, 131);
<p dir='rtl' align='right'>
تو کدی که واسه Pull Request میفرستی نباید اینجور کامنت‌ها باشه

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/Angular/src/app/home/contents/contents.component.scss
> +  /*display: inline-grid;*/
.

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/Angular/src/app/home/contents/contents.component.scss
> +  font-family: arsoo, serif;
<p dir='rtl' align='right'>
بهتره تو کل سایت از یه فونت استفاده کنی؛ بنابراین font-family رو بذار تو body

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/Angular/src/app/home/contents/search-box/advance-search/advance-search.component.html
> +         (keyup)="passValue()">
<p dir='rtl' align='right'>
چون ما به انگلیسی کد میزنیم، بعضی وقتا ممکنه نوشته‌های فارسی مشکل‌ساز بشن
<br>
بهتره مثلاً تو فایل ts واسه هرکدوم یه متغیر درست کنی

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/Angular/src/app/home/contents/search-box/advance-search/advance-search.component.ts
> +
<p dir='rtl' align='right'>
اینا چون تکراریه دیگه من هر دفعه کامنت نمیذارم ولی خودت حواست باشه

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/FrontEnd/index.html
> +<!--</div>-->
.

2021-05-15 17:09 UTC, BijanEisapour commented on Phase11/SearchApp-API/.idea/.idea.SearchApp-API/.idea/.gitignore
> +/httpRequests/
<p dir='rtl' align='right'>
فک کنم حواست نبوده پوشۀ idea رو ignore نکردی

2021-05-29 13:59 UTC, ahessamb commented on Phase11/Angular/src/app/home/contents/contents.component.scss
> +  font-family: arsoo, serif;
متوجه نشدم. الان من دو سه تا فونت مختلف دارم استفاده می کنم خب ، بده؟ یا باید عوضش کنم؟

2021-06-16 09:04 UTC, merged